### ISSUE TITLE
Importing flvers that use textures from multiple maps

### ISSUE THREAD

**Issue by fromsoftserve** [Grimrukh/soulstruct-blender#1]
When importing a flver file that references textures from for example m10 tpf and m12 tpf, if I have the m10_01 map selected in Blender Soulstruct, it will load the m10 textures just fine, but throw an error for the m12 textures the flver references like some foliage for Undead Burg flvers. I've had to manually grab the m12 textures it references, convert them to PNG, and throw them in the PNG cache folder I created. Then I reimport the flver and it loads just fine. Perhaps I'm missing the option to designate both m10_01 and m12_01 maps at the same time for loading said mappiece. Thank you for this tool btw. It's amazing.

**Comment by Grimrukh** [comment]
This is fixed in v1.0.1. If Soulstruct cannot find a texture in the right map (which is naughty but sadly occasional behavior), it will use the texture prefix (e.g. 'm10_') to check other map textures.
