### ISSUE TITLE
Import player character for equipment and anims but get "Cannot import FLVER from CHRBND: c0000.chrbnd.dcx. Error: need at least one array to concatenate."

### ISSUE THREAD

**Issue by stevyb95** [Grimrukh/soulstruct-blender#11]
Cannot import FLVER from CHRBND: c0000.chrbnd.dcx. Error: need at least one array to concatenate.

Import C0000 for fbx export with some equipment and animations maybe but get this error on character import of c0000

**Comment by Grimrukh** [comment]
Fixed in the version going up later today :)

**Comment by stevyb95** [comment]
You’re a gem!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
