### ISSUE TITLE
UI issue with importing equipment lol

### ISSUE THREAD

**Issue by stevyb95** [Grimrukh/soulstruct-blender#13]
![image](https://github.com/Grimrukh/soulstruct-blender/assets/3580357/2ad8c624-a422-457a-97cf-ca6642a9cc67)

 this menu works in this image...
 
 
![image](https://github.com/Grimrukh/soulstruct-blender/assets/3580357/93a073fc-0275-4b26-80a9-70e010f8fbe8)

but in this one it hits the edge of my monitor and i cannot see any of the leg data of the equipment because the list is just too large resulting in me having to use the "Import FLVER" button anyway lol :p

![image](https://github.com/Grimrukh/soulstruct-blender/assets/3580357/d7a52deb-cf7a-4449-86e4-e67e9697522e)
also lastly the facegen doesnt appear to import the face model either just the skeleton now the lady looks like squall from ff8
![image](https://github.com/Grimrukh/soulstruct-blender/assets/3580357/54d14948-5b27-4cc6-a1eb-e37ac34da239)
![image](https://github.com/Grimrukh/soulstruct-blender/assets/3580357/f88f1863-c22f-4357-8a41-2cc419a6af79)

**Comment by Grimrukh** [comment]
Fixed in v1.2, which now just uses the browser window to let you pick the FLVER from the relevant game folder when possible.
