### ISSUE TITLE
Cannot import FLVER: m2740B0A10.flver.dcx ERROR: dictionary changed size during iteration.

### ISSUE THREAD

**Issue by stevyb95** [Grimrukh/soulstruct-blender#14]
![image](https://github.com/Grimrukh/soulstruct-blender/assets/3580357/0bba6086-c100-4b67-837f-ddc766654708)
Cannot import FLVER m2740B0A10 (MSB m2740B) under map stem m10_00_00_00 dictionary changed size during iteration

**Comment by Grimrukh** [comment]
Should be fixed in v1.2.
