### ISSUE TITLE
Feature Request : Working Directory for quick export

### ISSUE THREAD

**Issue by Dynamic-src** [Grimrukh/soulstruct-blender#17]
### Add a working directory independent of the game directory for the quick export feature.

Use case :
I use Mod Organizer 2's virtual file system to avoid modifying the game files directly, so i can launch a unmodded instance when i want.
Quick export would basically create the folder required in the working directory.
So quick import (MSB) would load the mesh from "DARK SOULS REMASTERED\map\(mapfoldername)\(modelname).flver.dcx"
And quick export (msb) would export the mesh to "WORKING DIRECTORY\map\(mapfoldername)\(modelname).flver.dcx"
When exporting Havok collision, it would write the full binder to the working directory

End goal is a easy way to ship only modified files when sharing a mod.

How it would look :
![UI](https://github.com/Grimrukh/soulstruct-blender/assets/64365493/4d0efeb1-0975-48ff-97a2-0000a010c0b9)

Could also add an "import from Working directory" checkbox to the msb import.
In this mode there would be no need to create a .bak file since the game folder would be untouched

**Comment by Grimrukh** [comment]
This has now been implemented after much work in v1.3.0. You can set a Game directory and a Project directory. Exported files will be written to the Project (if given) and, if `Also Export to Game` is checked, to the Game directory as well. When importing files, options from both Game and Project will be offered if possible, and there's a bool `Prefer Import from Project` to control how to handle cases where only one can be used.
