### ISSUE TITLE
Cannot seem to export edited m2030B1 (map m10_01)

### ISSUE THREAD

**Issue by LibretroAdmin** [Grimrukh/soulstruct-blender#19]
Not sure if doing something wrong. After making an edit and clicking on 'Export Mappieces', the following error message occurs "Cannot get exported FLEVER. Error: Cannot have more than 4 UV maps in a vertex array (got 6).".
![test](https://github.com/Grimrukh/soulstruct-blender/assets/105389611/aeeddb53-75a1-49f3-a6a1-3bbfa771dac4)

Using the latest version of soulstruct-blender (https://github.com/Grimrukh/soulstruct-blender/releases/tag/v1.2.4)

**Comment by Grimrukh** [comment]
I've replicated this. Will investigate.
