### ISSUE TITLE
FBX edits to HKX animation: Exported result twitches once in game

### ISSUE THREAD

**Issue by DS-Path** [Grimrukh/soulstruct-blender#20]
Issue found on v 1.2.4 with c3430 (Red Wyvern) - unsure yet if this is character specific

**Repro Steps:**
- Open Blender (V3.6)
- Import c3430.chrbnd.dcx
- Import a00_0000.hkx from c3430.animbnd.dcx (its idle animation)
- Export the data into FBX format containing the animation data
- Modify FBX animation in non blender editor (Example: Maya 2022)
- Save modifications done to the FBX file
- Import the FBX file back into Blender
- Export the animation either as *.hkx loose file or as part of its animation-binder file
- Preview the animation in an animation viewer or in-game

**Outcome:**

- While the animation plays fine in the editor if re-imported from the game, the result preview in an animation viewer or in game will often have twitching that is not present at all when the animation is imported back into blender

- Suspecting this is some sort of phantom data visible to the game but not to Blender

**Pre-report Investigation**

- It would seem that the twitching and errors always seem to fall on half frames. Example: frame 112.5/220
- This is not dependent on weather or not the animation is exported using the 60FPS option toggle on or off
- I tried the following actions: adding a keyframe on the twitching areas on all channels (ineffective), pruning keyframes the affected areas (ineffective), removing W-Quaternion Rotation data (ineffective, and did cause further issues)
- There are also instances where the animation will be completely scronched - that may have to do with the format used for the FBX - I recall getting the animation working with FBX 2014/2015, but also what you select when exporting the data seem to matter. Said scronching is reflected on animation re-import, so likely this is workflow issue

_I'm positive this is a plug-in issue, but this could also be me doing things in a very, very unorthodox/wrong way. Plus the plug-in was perhaps never intended to support an out-of-blender workflow at all, so no guilt if this is a non issue. Free to close it as "Won't Do" if necessary
I'm more then happy to support the fixing of this issue with files, captures and as much information as possible_
_@Path_Mod_

**Comment by DS-Path** [comment]
Showcasing the issue's nature

Reference pic: Data read in DSAnimStudio V4.9.7
![Neck Issue](https://github.com/Grimrukh/soulstruct-blender/assets/150955973/0c572b6e-d570-432b-9800-d86177774adf)
Reference pic: same data imported back to blender, same frame - no deformation
![image](https://github.com/Grimrukh/soulstruct-blender/assets/150955973/cc7209ab-4a1a-480b-81ff-0e6d6d57e6ad)

**Comment by Grimrukh** [comment]
This has been fixed for the next big update, coming soon!

**Comment by DS-Path** [comment]
Awesome! Feel free to close the issue
Looking forward to the next version.
Unsure if an ETA is public yet, but I'll be patient
