### ISSUE TITLE
Can't load FLVER after 4.0 blender update.

### ISSUE THREAD

**Issue by McThizzin** [Grimrukh/soulstruct-blender#21]
Can't load map, char, or object FLVER after 4.0 blender update. Have reinstalled Blender, Dark Souls and SoulstructIO and get the same error.
![blender_cYzt4YzsKL](https://github.com/Grimrukh/soulstruct-blender/assets/151303101/48539f47-4647-4809-b61b-bb508ad16726)

**Comment by Grimrukh** [comment]
Blender 4.0 is not yet supported due to exactly this issue. Will be fixed very soon!

**Comment by Grimrukh** [comment]
v1.3.3 now supports Blender 4.0.
