### ISSUE TITLE
cant import all animations using "all animations" option importing player animations manually using "import hkx anim"

### ISSUE THREAD

**Issue by stevyb95** [Grimrukh/soulstruct-blender#22]
cant import all animations using "all animations" option importing player animations manually using "import hkx anim" option it only imports 2 animations before failing by the looks of things

blender 3.6.5

--------------------------------------------------------------------------------------------------------------------------------

![image](https://github.com/Grimrukh/soulstruct-blender/assets/3580357/f12641d8-eb95-4a67-a1b4-f41373e672ec)

------------------------------------------------------------------------------------------------------------------------------------

![image](https://github.com/Grimrukh/soulstruct-blender/assets/3580357/c3956030-a81c-4738-a125-82b0914e49c9)

------------------------------------------------------------------------------------------------------------------------------------

![image](https://github.com/Grimrukh/soulstruct-blender/assets/3580357/3803b68f-f469-47b7-bb75-6bb80b8b53c5)

**Comment by Grimrukh** [comment]
This is fixed in v1.3.2. Animations should no longer fail to import, and even if they do, they won't interrupt others when importing all.
