### ISSUE TITLE
"Load All Animations" cancels remaining imports if it cannot import an animation

### ISSUE THREAD

**Issue by SlendyOfDaMawn** [Grimrukh/soulstruct-blender#23]
Issue present in **Blender 4.0**

Attempting to use _Load All Animations_ will not import remaining animations if one of them cannot be imported.

Is this intentional? I'm not sure.

**Comment by stevyb95** [comment]
yeah it seems to error out on *most* non root motion animations such as resting at bonfires (idle) but not the sitting at or getting up from motions... very odd xD

a00_7700 works - sitting at bonfire
a00_7701 does not work - idle rest loop from 7700
a00_7702 works - standing up from 7701
contained in c0000_a00_lo.anibnd

**Comment by SlendyOfDaMawn** [comment]
Yeah, this makes importing large amounts of animations an absolute nightmare.
I hope this gets fixed soon.

**Comment by Grimrukh** [comment]
This is fixed in v1.3.2 (and all those animations that were failing should no longer fail anyway).
