### ISSUE TITLE
[Animation] - Importing character rotation animation assets does not import their movement data and it gets lost on export

### ISSUE THREAD

**Issue by DS-Path** [Grimrukh/soulstruct-blender#24]
Issue found on V 1.2.4 using Blender 3.6

**Repro Steps:**

- Import any character Flver file into Blender
- Import that character's animation binder
- Load any rotation animation [a00_06xx]

**Outcome:**

- Imported animation loses rotation movement data - this does not seem to happen with forward/backwards animation cycles
- exporting the animation verbatim or edited to the game also causes loss of rotation data, causing the character to be static in anim-viewers/game

**Pre-Report Investigation:**

Rotation could potentially be re-introduced manually on the anim-edit. 
So far I got the character to rotate in animation again, but said rotation isn't translated into motion. Possibly because I've targeted the wrong bone.
The risk is, also, that the user can and will mess up the rotation angles leading to in-game issues.

**Comment by Grimrukh** [comment]
This is fixed in v1.3.1.
