### ISSUE TITLE
"Import Map Piece Part" and "Import ALL Map Piece Parts" Appear to not function properly.

### ISSUE THREAD

**Issue by Mrmoneybags1000** [Grimrukh/soulstruct-blender#27]
"**Import Map Piece Part**" remains grayed out after selecting a map piece. "**Import ALL Map Piece Parts**" only imports some of the map pieces in a map, every other map piece fails to import.
![Screenshot (35)](https://github.com/Grimrukh/soulstruct-blender/assets/155201471/1dd63f4e-e972-42f4-8a7d-21adb4b3f5c5)

**Comment by Grimrukh** [comment]
These issues should be fixed in 1.3.5.
