### ISSUE TITLE
[Animation] - Animation glitches occur on custom animation exported with the Tool - V1.4

### ISSUE THREAD

**Issue by DS-Path** [Grimrukh/soulstruct-blender#28]
Issue found in V 1.3.4
Repro Steps:

- Export any custom animation from the blender plug-in to an animation binder
- Load the animation in an Anim-tag editor
- Add an SPFX modulating the animation speed (for example 30% speed)
- Play the animation in the viewer or test it in game

Result:
- The animation glitches out

_Pre report Investigation:
This seems to happen only on animation slow-downs so far
I am assuming the glitchy animation fix rolled out in v 1.3 was partial, since animations at full speed work as intended now.
The tool may have never been designed to support animation modulation via spfx driven speed-ups/slow-downs of custom assets
If so I don't think this is stated anywhere in the tool's description or known issues._

Capture:
https://github.com/Grimrukh/soulstruct-blender/assets/150955973/b7e72532-b7d2-4133-95d8-cb463058b599

**Comment by DS-Path** [comment]
Just tested speed ups as well for the sake of completion/consistency
Issue is present on speed-ups as well

**Comment by DS-Path** [comment]
Yet another addendum:
I tried removing all tags of a custom animation.
While glitches are not visible during normal playback, they are still there. They become visible if the user were to scroll through the animation
Once more, the glitches seem to happen at 1/2 frames (Example on the picture below)
![image](https://github.com/Grimrukh/soulstruct-blender/assets/150955973/2cdc749f-e38d-4287-b7e3-f9aa202705ca)

Hope this helps!

**Comment by DS-Path** [comment]
Issue persists on V 1.4
It is getting more stable, but jitter still happens

**Comment by DS-Path** [comment]
Attempted a test with a different character
c2500 and an edit to Anim ID 0
Edited the Animation by twisting the spine joint by 90 degrees and re-exported the animation within the binder with a new ID
Twitching still occurred on the arms joint

**Comment by Grimrukh** [comment]
I've now replicated this issue, and yes, it seems to be related to between-frame interpolation.

My guess is the usual culprit: sign flips in the exported rotation quaternions from Blender. Will look into it and do what I can.

**Comment by Grimrukh** [comment]
This should now be fixed in v1.4.1! I can't replicate it anymore, at least.
