### ISSUE TITLE
Dark Souls 2 support planned?

### ISSUE THREAD

**Issue by ReindeerFloatilla** [Grimrukh/soulstruct-blender#3]
Question. The Github page says support for Dark Souls 1 PTDE, Dark Souls 3 and Elden Ring are planned. Is Dark Souls 2 support planned at any point? It's the game that I'm personally the most interested in utilizing this addon for.

**Comment by Grimrukh** [comment]
Dark Souls 2 FLVER models will almost certainly be supported. Supporting different versions of Havok is much more difficult, so we'll have to see how that goes for collisions and animations. The README will be updated soon to make this clear.

**Comment by ReindeerFloatilla** [comment]
Thank you so much for answering. I'm so excited as I have very big plans for Dark Souls 2 custom levels.
