### ISSUE TITLE
Exported equipment meshes being blocky?  v1.4.1

### ISSUE THREAD

**Issue by BoboLLC** [Grimrukh/soulstruct-blender#31]
Exporting equipment files seems to work perfectly fine now, but a new bug has appeared.

Blocky/Choppy meshes: 
![Screenshot (57)](https://github.com/Grimrukh/soulstruct-blender/assets/108726830/9c7f3a77-9bc5-4955-bcb9-29bfff0bed2a)

I also exported a edited equipment piece into the game and the issue persisted.
![20240205142046_1](https://github.com/Grimrukh/soulstruct-blender/assets/108726830/30a3729c-4ad9-4b1f-a1bb-6d7c09a08306)

Honestly, I have no idea what could even be causing this issue. I checked the error logs and blender console, and nothing came up at all. I implore you to run some tests as well, because it might just be an issue somewhere on my end.

Also where do you have your errors logs kept? I couldn't find them after a bit of searching.

**Comment by Grimrukh** [comment]
Working on this; FLVER files handle normals very differently to Blender and obviously aren't being preserved at the moment (all vertex normals are just being set to their face normal).

**Comment by Grimrukh** [comment]
This is fixed in 1.5.0.
