### ISSUE TITLE
Error when trying to import any .mcg file

### ISSUE THREAD

**Issue by Skullman-G** [Grimrukh/soulstruct-blender#35]
![Bild_2024-03-13_180404208](https://github.com/Grimrukh/soulstruct-blender/assets/64651571/2d3c4b87-c885-4fc2-8b44-461cd55896de)

This error pops up whenever I try to import just any .mcg file.

I might also add that I only tested it with files from Dark Souls Remastered.

**Comment by Grimrukh** [comment]
This should finally be fixed in version 2.0!
