### ISSUE TITLE
Feature Request - Import object instances with map MSB import

### ISSUE THREAD

**Issue by vermadas** [Grimrukh/soulstruct-blender#37]
Thank you for all your work on this addon, it's a wonderful tool.

It would be great if there was an option to import all object FLVERs that are present in a map, with their corresponding locations/transforms.

**Comment by Grimrukh** [comment]
Working on this. (It's just slightly more complicated because objects can have multiple FLVERs.)

**Comment by Grimrukh** [comment]
MSBs are now fully supported for editing in version 2.0.
