### ISSUE TITLE
Parallax Occlusion Mapping broken on soulstruct edited flvers

### ISSUE THREAD

**Issue by fromsoftserve** [Grimrukh/soulstruct-blender#39]
I've recently been going through and adding parallax occlusion mapping to more surfaces, which has worked really well, except for any flver that I had previously edited in Blender Soulstruct. Everything is indentical to non-edited flvers where the parallax effect displays just fine. So, to test, I replaced the edited flver with the original unmodified file, enabled parallax through the flver, assigning the heightmap and changing the mtd used to M[DBH] for instance. Works perfectly.

Another thing I've found is Blender Soulstruct will warp existing parallax that was already in the game. M2280B1 in Undead Burg is the perfect example. It's existing parallax effect on the wall becomes warped and distorts when you tilt the camera but also looks incorrect by default. Replacing the editing flver with the unmodified file fixes the issue and the parallax looks ace again.

I'm not entirely sure why this is happening. I'm only removing a couple faces from a mesh, or filling a small mesh hole. Nothing major.

Here's a modified flver that refuses to have the parallax work despite having the correct setup:
[](https://drive.google.com/file/d/1cqNPEe7EmUmMPlXe0i4kH348n0p80OHz/view?usp=sharing)

here's a video showing the warping and incorrect parallax effect on the blender soulstruct edited flver:
[](https://drive.google.com/file/d/1buLhEWTp7PsDd188C0F33Ff34RKrW_k6/view?usp=sharing)

**Comment by fromsoftserve** [comment]
[https://drive.google.com/file/d/1buLhEWTp7PsDd188C0F33Ff34RKrW_k6/view?usp=drive_link](url)

**Comment by fromsoftserve** [comment]
and here's the flver shown in the video for reference:
[https://drive.google.com/file/d/1cqNPEe7EmUmMPlXe0i4kH348n0p80OHz/view?usp=drive_link](url)

**Comment by Grimrukh** [comment]
This is almost certainly caused by Blender exporting bad tangent data for meshes. Will look into it as soon as I can, might be a couple of weeks unfortunately.

**Comment by fromsoftserve** [comment]
ah, makes sense! sounds good! no rush, I know you're super busy. Appreciate all your hard work.

**Comment by Grimrukh** [comment]
Finally fixed!! Only tested it on that m2280B1A10 you mentioned but it was fairly straightforward, Blender tangents just needed rotating.

You can fix any dodgy Map Pieces by simply reopening them in Blender (if needed) and resaving them. All tangent data is created automatically on export from Blender.

I'll leave this open until you can confirm it's also fixed for your far more expansive g_Height models.

**Comment by fromsoftserve** [comment]
just saw this now! tried it out and it works perfectly. thank you so much for your efforts. they are greatly appreciated!
