### ISSUE TITLE
Any tips on how to use this safely(without getting banned) on the steam version?

### ISSUE THREAD

**Issue by nihilreich** [Grimrukh/soulstruct-blender#4]
Would just setting my game to launch in offline mode, backing up my saves (and turning off cloud saves) be enough? 

Been playing around with it for for an hour btw amazing job!! 

(I couldn't figure out where to pose such a simple question, can delete this post if this isn't the place, sorry in advance I'm not familiar with github.)

**Comment by Grimrukh** [comment]
Thanks! Yes, launching your game (or Steam itself) in Offline Mode should prevent you from being banned.

Backing up your saves shouldn't be necessary for the types of asset edits enabled by Soulstruct for Blender, but regardless, I'll never recommend NOT doing it.
