### ISSUE TITLE
ImportError: parent 'soulstruct_havok' not in sys.modules

### ISSUE THREAD

**Issue by Kindslaps** [Grimrukh/soulstruct-blender#40]
![Screenshot from 2024-05-03 02-33-35](https://github.com/Grimrukh/soulstruct-blender/assets/168820527/8b32bfe6-70f3-4ddf-b6f0-8e281572343b)
Hello, I get this error message when trying to enable "Import-Export: Soulstruct" in the Add-ons menu, I have tried everything I can to fix this. Maybe I missed something.
Would appreciate any help :P

**Comment by drakomatic** [comment]
I'm getting the same error, I'll try downgrading to blender 3.6 and see if that helps

**Comment by drakomatic** [comment]
Can confirm, error is blender 4.1 specific

**Comment by Kindslaps** [comment]
I can also confirm that this was a Blender 4.1 Issue.
Thanks for the help!! :v
