### ISSUE TITLE
Material representation issues

### ISSUE THREAD

**Issue by K0pter** [Grimrukh/soulstruct-blender#41]
Hello, I just started playing around with the toolkit- and getting situated, but I quickly noticed some issues with the generated materials that are being applied currently. 

Purely looking at DSR atm btw.

I might've just screwed something up somehow, since I'm still somewhat of a Blender noob, but the normal generation seemed a bit off when looking at the material nodes. 

So currently, the bumpmap nodes use the "sRGB" color space, when they should really be using the "Non-Color" one, due to normal maps being linear. Then this was fed into a "Normal Map" node with intensity set to "0.4", which seemed a bit odd to me as well. Then I had a look at the normal map assets, which had uniform black colors in their blue/z channels, and normally it should be white if anything.

SO- I ended up testing a couple things back and forth, and figured it would be nice to be able to quickly flip the channels as well in the material when previewing in case the surface still doesn't look quite right when previewing- so here's a packed little node group I came up with to mitigate and hopefully correct most of the issues we're currently seeing.

![image](https://github.com/Grimrukh/soulstruct-blender/assets/29183970/ebb6314f-7564-48c3-8bce-68121d36684e)

And then the channel flip node:

![Uploading image.png…]()

Pretty simple. 

On another note, I was also questioning the "IOR" to be set any higher than 1, or there was a pretty nasty glaze/ glare effect showing up on the surfaces. Maybe default to 1 instead due to how simple the materials are in the game?

Anyway, not sure where else to write this, hopefully it helped out to some degree!

**Comment by K0pter** [comment]
![image](https://github.com/Grimrukh/soulstruct-blender/assets/29183970/ac6b537e-10ee-42f1-8220-f7ebc648a190)

Quick snap of the result

**Comment by K0pter** [comment]
Oh yeah, one more thing I forgot to mention- it seems as if by default the green channel should be flipped when viewing in blender!

**Comment by Grimrukh** [comment]
A bit slow to reply, but thanks for the investigation, I've integrated these corrections into the add-on now!
