### ISSUE TITLE
Loading animations works fine, but using "Load All Animations" makes them all fail.

### ISSUE THREAD

**Issue by SlendyOfDaMawn** [Grimrukh/soulstruct-blender#42]
Attemping to use _"Load All Animations"_ makes every single one throw out this error:

`Error occurred while importing HKX animation: 'NoneType' object has no attribute 'name'`

Tested using:
**Dark Souls Remastered
Elden Ring**

![image](https://github.com/Grimrukh/soulstruct-blender/assets/34933487/54fee067-eb8e-4c32-9042-abc62225d1ad)

**Comment by betazerotwo** [comment]
That's probably after the update, so it probably won't work.

**Comment by Grimrukh** [comment]
Finally fixed this in v1.9.0!
