### ISSUE TITLE
Error when trying to load Soulstruct Addon to Blender

### ISSUE THREAD

**Issue by HeilingerKrest** [Grimrukh/soulstruct-blender#43]
I get this error when trying to load the Soulstruct Addon. I'm using blender 4.1 (Windows). 

Here is a screenshot : https://ibb.co/Sfg1jb0

**Comment by oxixxixo** [comment]
didn't check your screenshot but I was having the same issue and fixed it by downgrading to blender 4.0.2

**Comment by Grimrukh** [comment]
Blender 4.1 should now be OK with v1.9.0!

**Comment by draganczukp** [comment]
Hi, I'm getting this error with Soulstruct v1.9.1 and Blender 4.1.1 (latest download as of 5 minutes ago). Works perfectly in Blender 4.0.2
