### ISSUE TITLE
Version 1.9.0 fails to enable.

### ISSUE THREAD

**Issue by Mrmoneybags1000** [Grimrukh/soulstruct-blender#44]
When attempting to enable the new version in blender, it just throws these errors. Oddly this only happens with 1.9.0, as 1.8.0 enables just fine. (tested with fresh installs of blender 3.6.5, 4.0.2, and 4.1.1)
![Screenshot (56)](https://github.com/Grimrukh/soulstruct-blender/assets/155201471/3478839a-b49c-4fbb-99b4-478003d2d07e) 
![Screenshot (57)](https://github.com/Grimrukh/soulstruct-blender/assets/155201471/2d2eb64b-f7ca-447b-9ba2-ebe49079fc86)

**Comment by Grimrukh** [comment]
My bad! This should be resolved in 1.9.1.
