### ISSUE TITLE
Blender 3.6.12 can't import animation

### ISSUE THREAD

**Issue by RotaryHeart** [Grimrukh/soulstruct-blender#46]
My buttons for importing animation are disabled. Tried upgrading to latest blender 4x but installation is failing

![image](https://github.com/Grimrukh/soulstruct-blender/assets/2595674/059cf3d7-f1ec-4fe7-b265-30e1d050b105)

**Comment by Grimrukh** [comment]
You have to select an Armature object for this operator to be useable! That's the c2790 parent object in your view there.
