### ISSUE TITLE
Updating the tool for ER Shadow Of The Erdtree support

### ISSUE THREAD

**Issue by ControVR** [Grimrukh/soulstruct-blender#48]
Any ETA on adding support for SOTE? I've been trying to import some characters and it can't seem to find the matxml's in the MATBINBND, and a few other things I've forgotten the names of.

**Comment by Grimrukh** [comment]
Absolutely, planning on adding a LOT of Elden Ring support in the coming weeks.

**Comment by ControVR** [comment]
Fantastic, can't wait 👍
