### ISSUE TITLE
Issue/Question Regarding Vertex Weighting

### ISSUE THREAD

**Issue by BoboLLC** [Grimrukh/soulstruct-blender#52]
This is the error I received after working on a model. 
-  Cannot create exported FLVER from Blender Mesh 'c2400'. Error: Vertex cannot be weighted to 5 bones (max 1 for Map Pieces, 4 for 
others).

I understand everything about the error and what went wrong. I'm just curious if there's a possible way of locating the vertex's that are improperly weighted. From searching online I couldn't find any solutions relating to this program or this type of error in any real way.

I searched in your code to see what was used to find the improperly weighted vertex's, but due to my limited knowledge of coding I am unsure of how to input your scripts into a solution.  I wish there was some way of highlighting the vertex's that are improperly weighted.

All I'm curious of is if there is a simple solution you know of, or if I should just start from scratch and re-edit the model from the ground up once again.

Thank you for your time.

**Comment by Grimrukh** [comment]
I feel your pain. I'm pretty sure I can at least add a vertex index to that error report!

**Comment by Grimrukh** [comment]
Soulstruct 2.0 now reports the index of a vertex with invalid weights.
