### ISSUE TITLE
Can't export collision files mopper.exe did not run successfully.

### ISSUE THREAD

**Issue by TheChristopherous** [Grimrukh/soulstruct-blender#53]
Installed the latest patch of soulstruct-blender and blender.
I have tried downgrading but i still get the same error.
Cannot get exported hi/lo HKX for 'h1113B1A10 Hi Submesh 0'. Error: `mopper.exe` did not run successfully. Return code: 3221225781

**Comment by hglad** [comment]
Hi, did you figure out how to get around this? I'm getting the same error when trying to export a collision. Using version 2.4.0 of the plugin and Blender 4.4.3.
```
Traceback (most recent call last):
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\4.4\scripts\addons\io_soulstruct_lib\soulstruct_havok\utilities\mopper.py", line 27, in mopper
    raise RuntimeError(f"`mopper.exe` did not run successfully. Return code: {ex.returncode}")
RuntimeError: `mopper.exe` did not run successfully. Return code: 3221225781

```

**Comment by Vmarcelo49** [comment]
i got the same problem, mopper.exe needs Microsoft visual cpp 2010 x86 and x64 @hglad
