### ISSUE TITLE
Import error 

### ISSUE THREAD

**Issue by ulaluuuume** [Grimrukh/soulstruct-blender#6]
![errorr](https://github.com/Grimrukh/soulstruct-blender/assets/149778030/4a3aa2aa-0b08-420e-931b-965263c44cbc)

Hi,

when I  try to check the Import-Export: Soulstruct box in the add-ons menu, I get this error report: what can I do?
Thank you so much 💯

**Comment by Grimrukh** [comment]
You have to install Blender addons in `AppData/Roaming/Blender Foundation/Blender 3.X/scripts/addons` (creating it if needed).

If you use `Program Files`, Soulstruct may not have write access to its own folder for logs and other temporary files.

I've made this clearer in the README instructions :)

**Comment by ulaluuuume** [comment]
Sorry, @Grimrukh 

I've installed the addons in the folder `AppData/Roaming/Blender Foundation/Blender 3.X/scripts/addons` 
but, when I try to import it from Blender, I get this log:

`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'io_soulstruct'

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'io_soulstruct'

`

**Comment by Grimrukh** [comment]
Do you mean when you try to enable it in Preferences, or literally trying to import it with a Python script in Blender?

(Also, just checking, you didn't literally put it in a folder called `Blender 3.X` right? That should be replaced with whatever your Blender version is.)

**Comment by ulaluuuume** [comment]
> Do you mean when you try to enable it in Preferences, or literally trying to import it with a Python script in Blender?
> 

Yes, the error appears when I try to enable the addons in Preferences
> (Also, just checking, you didn't literally put it in a folder called `Blender 3.X` right? That should be replaced with whatever your Blender version is.)

Nono, I have unzipped the folder in 
`C:\Users\"myusername"\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons`

**Comment by Grimrukh** [comment]
Hmm, so there is definitely a folder `scripts\addons\io_soulstruct` that contains `__init__.py` and other files? There isn't an extra nested folder?

**Comment by ulaluuuume** [comment]
Yes, here it is:
![schermata](https://github.com/Grimrukh/soulstruct-blender/assets/149778030/6f66c684-6bfa-46c4-a0e8-a7267bd3301f)

**Comment by EdgedEnd** [comment]
i met the same problem and i wonder if you have tackle it?

**Comment by dhafer4450** [comment]
have anyone know why does this happen it also happened to me and i dont know how to fix it

**Comment by SUKOTTO5830** [comment]
well I am having the same problem, hope it can be solved

**Comment by dhafer4450** [comment]
try downgrading your blender version. It worked for me after using blender
version 4.0
