### ISSUE TITLE
NotADirectoryError when importing/exporting Bloodborne flver on Soulstruct 2.0

### ISSUE THREAD

**Issue by fromsoftserve** [Grimrukh/soulstruct-blender#62]
Just trying to import a Bloodborne flver and then export it with or without any edits, as I know prior versions of Soulstruct couldn't export them yet. Keep running into this issue on both Blender 4.1 or 4.2. 

![Screenshot 2024-09-08 160832](https://github.com/user-attachments/assets/b7e74107-bc57-41d1-924b-aecf23f0aaa8)

I've made sure I'm selecting the root folder of Bloodborne (dvdroot_ps4) in the general settings. Unless I'm missing something basic, which is likely lol.

**Comment by fromsoftserve** [comment]
Oh so it did just work if I selected export mappiece, instead of export loose flver which is what I had become used to with exporting DSR mappieces.

**Comment by Grimrukh** [comment]
Hmm, strange. So to clarify, you get that error in the screenshot when you click `Export Loose FLVER`? Because the error is being raised from the `Import Map Piece` operator (or is the error happening when you try to re-import the loose exported FLVER?).

**Comment by Grimrukh** [comment]
Regardless, I can definitely see at least one issue in the code here that I'll fix, which could be causing this.

**Comment by Grimrukh** [comment]
OK, I've replicated this - it looks like the FLVER export does actually work (the file appears), but the error is a separate issue occurring in the polling (availability check) of the `Import Map Piece` operator.

**Comment by Grimrukh** [comment]
Fixed in 2.0.1.
