### ISSUE TITLE
Name "TRSTransform" not defined!! Error when exporting DSR animations

### ISSUE THREAD

**Issue by Skullman-G** [Grimrukh/soulstruct-blender#64]
![image](https://github.com/user-attachments/assets/d5e96cd1-214a-4b4d-ab95-db83215bff60)
I got this error message whenever I try to export any DSR animation. Haven't tested it with the other games yet, but I have a suspicion that it's the same there. Anyone know what this is about? Can it be fixed manually or does it require a new patch of this tool?

**Comment by Grimrukh** [comment]
Working on this!

**Comment by Grimrukh** [comment]
Finally got to this, animation support for DSR should now be restored!
