### ISSUE TITLE
Error when enabling plugin after installing 2.01 on Blender 4.2.1

### ISSUE THREAD

**Issue by RusticKey** [Grimrukh/soulstruct-blender#66]
I received an error

cannot import name 'import_arbitrary_module' from 'soulstruct.utilities.files' (...\Blender\4.2\scripts\addons\io_soulstruct_lib\soulstruct\utilities\files.py)

when trying to enable the plugin on 4.2.1.

Also probably cosmetic, but installing the 2.0.1 add-on shows the version as 2.0.0 in the add-ons page.

**Comment by mdmrk** [comment]
I had errors when upgrading version, just deleted add-on manually and fresh installed it

**Comment by RusticKey** [comment]
I've tried manually deleting the old add-ons from AppData, then reinstalled and it fixed the issue. Thanks.
