### ISSUE TITLE
Texture issue when modifying Demon's Souls flvers

### ISSUE THREAD

**Issue by fromsoftserve** [Grimrukh/soulstruct-blender#73]
I've had this happen with a few flvers so far. The one attached is 3030b0 from the Nexus. All I did was bevel the edges on the stairs, which did work correctly. However, the wall right nearby turned purple. Then I fixed a mesh hole on the level right above, and then the floor there also turned purple. Must be some sort of material thing I export? I am using the latest soulstruct for blender that was updated yesterday. I'm going to edit a few more in different maps and see if it happens again.
![Screenshot 2024-09-30 141732](https://github.com/user-attachments/assets/b73e8023-20d6-4ad8-87d4-8a86c4a0e9d4)

here's the modified file: [](https://drive.google.com/file/d/17qKC7ldIXuRyaohxWSRvaWNzPJJkZYe3/view?usp=sharing)

**Comment by Boczekek** [comment]
I think there is something wrong with UVs
![Screenshot 2024-10-06 165445](https://github.com/user-attachments/assets/d5909969-0bcb-403b-87c4-95f20c03ed5f)

**Comment by Grimrukh** [comment]
This should be fixed in v2.1.8; I was exporting corrupted vertex array layouts for some DeS map materials :/
