### ISSUE TITLE
Error on importing DeS models

### ISSUE THREAD

**Issue by MaxStive** [Grimrukh/soulstruct-blender#76]
Error "ValueError: "FLVER" version 20 is not supported. Must be >= 0x20000"
Who can help with this problem
![Снимок экрана 2024-10-05 131426](https://github.com/user-attachments/assets/ca82e650-fa6f-49c0-9dfe-6c72b3fdb470)
?

**Comment by Grimrukh** [comment]
Which import operator/button are you using? Is the game definitely set to Demon's Souls? It looks like it's trying to import a DeS FLVER as a newer game format.

**Comment by MaxStive** [comment]
I use the file tab in bottom of window

**Comment by f0sterz** [comment]
Use N tab

**Comment by MaxStive** [comment]
Thank you, now i can import DeS models (fun fact: in files of addon DeS folder named incorrect)
