### ISSUE TITLE
DSR game crashes when using any exported animation files

### ISSUE THREAD

**Issue by Skullman-G** [Grimrukh/soulstruct-blender#78]
Exporting the animation files seems to work fine. But no matter which export option I choose, the game will always crash when the area with the modified enemy is loaded.

I thought it might be because of how I changed up the keyframes, but it even crashes when you just import and directly export the vanilla animation without changing anything.

It still can be viewed in the DS Anim Studio though.

**Comment by Grimrukh** [comment]
This should now be fixed in 2.1.6.
