### ISSUE TITLE
A11_snow.mtd causing issues upon export with Painted World flvers (DSR)

### ISSUE THREAD

**Issue by fromsoftserve** [Grimrukh/soulstruct-blender#80]
Trying to edit m2030B0A11 and upon export it gives this error:
![Screenshot 2024-10-11 150410](https://github.com/user-attachments/assets/3adb9f71-83b3-4a64-b1cf-50b98c96ffb9)

specifically it's the a11_snow.mtd and a11_snow_stair.mtd that's causing issues since it is the only mtd I know of in the game that has 3 bumpmaps. If I check "allow missing textures" this is what happens to the material entry in question:
![Screenshot 2024-10-11 151146](https://github.com/user-attachments/assets/f58d397f-387d-4865-8f17-94de4c4e2ea6)

So it creates a duplicate "g_bumpmap3" it seems. And in game of course the specific surface is broken. 
![Screenshot 2024-10-11 151241](https://github.com/user-attachments/assets/04bd543a-9063-412b-a9c1-449aaf09f1d4)

**Comment by fromsoftserve** [comment]
now, I wonder if it's because I swapped to the a11_snow.mtd vs the standard a11_snow[L].mtd since I'm likely the only jabronie disabling a lightmap wholesale, but is necessary in my very specific case with DSR Shader Overhaul being build into DSRR and so disabling the lightmap in the flver allows illumination on top of shadows. super, super niche case here lol

**Comment by Grimrukh** [comment]
This should be fixed in 2.1.6. It was just a straightforward bug happening on import with two copies of the `g_Bumpmap_3` texture (Main 2 Normal) being added to the Blender material; nothing specific to your goals, I believe!
